// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuministroProvisiones.INFRAESTRUCTURE.Data.Context;

#nullable disable

namespace SuministroProvisiones.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SuministroProvisiones.DOMAIN.Entities.SolicitudSuministro", b =>
                {
                    b.Property<int>("SolicitudSuministroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudSuministroId"), 1L, 1);

                    b.Property<int>("CantidadUnidades")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<double>("LatitudPuntoDestino")
                        .HasColumnType("float");

                    b.Property<double>("LongitudPuntoDestino")
                        .HasColumnType("float");

                    b.Property<string>("TipoClima")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SolicitudSuministroId");

                    b.ToTable("SolicitudSuministro");
                });

            modelBuilder.Entity("SuministroProvisiones.DOMAIN.Entities.SolicitudSuministroResponse", b =>
                {
                    b.Property<int>("SolicitudSuministroResponseId")
                        .HasColumnType("int");

                    b.Property<int>("CantidadProvisionesEntregar")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraEntrega")
                        .HasColumnType("time");

                    b.Property<double>("LatitudPuntoOrigen")
                        .HasColumnType("float");

                    b.Property<double>("LongitudPuntoOrigen")
                        .HasColumnType("float");

                    b.Property<int>("SolicitudSuministroId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TiempoEstimadoEntrega")
                        .HasColumnType("time");

                    b.HasKey("SolicitudSuministroResponseId");

                    b.ToTable("SolicitudSuministroResponse");
                });

            modelBuilder.Entity("SuministroProvisiones.DOMAIN.Entities.SolicitudSuministroResponse", b =>
                {
                    b.HasOne("SuministroProvisiones.DOMAIN.Entities.SolicitudSuministro", "SolicitudSuministro")
                        .WithOne("SolicitudSuministroResponse")
                        .HasForeignKey("SuministroProvisiones.DOMAIN.Entities.SolicitudSuministroResponse", "SolicitudSuministroResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitudSuministro");
                });

            modelBuilder.Entity("SuministroProvisiones.DOMAIN.Entities.SolicitudSuministro", b =>
                {
                    b.Navigation("SolicitudSuministroResponse");
                });
#pragma warning restore 612, 618
        }
    }
}
